### ISSUE TITLE
Initial Release TODO:

### ISSUE THREAD

**Issue by andrewvc** [elastic/go-lookslike#2]
- [x] Add basic examples to README.md https://github.com/elastic/go-lookslike/pull/6
- [x] Add Travis CI Support
- [x] Add code linting via Hound
- [ ] ~~Add benchmarks for simple scenarios~~ (I think we can wait on this)
- [x] Split into multiple packages for future extensibility https://github.com/elastic/go-lookslike/pull/3
- [x] Better handle primitive/nil types #5 
- [x] Add Apache2 License https://github.com/elastic/go-lookslike/pull/7
